
import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
import path from 'path';

function parseEnv(filePath: string) {
    const content = fs.readFileSync(filePath, 'utf-8');
    const env: Record<string, string> = {};
    content.split('\n').forEach(line => {
        const match = line.match(/^([^=]+)=(.*)$/);
        if (match) {
            env[match[1].trim()] = match[2].trim();
        }
    });
    return env;
}

const envConfig = parseEnv(path.resolve(process.cwd(), '.env'));
const supabaseUrl = envConfig['NEXT_PUBLIC_SUPABASE_URL'];
const supabaseKey = envConfig['SUPABASE_SERVICE_ROLE_KEY'];

if (!supabaseUrl || !supabaseKey) { process.exit(1); }

const supabase = createClient(supabaseUrl, supabaseKey);

const MILESTONES = [
    { title: "Kickoff & Requirements", status: "completed", due_date: "2024-12-22" },
    { title: "Environment Setup", status: "completed", due_date: "2024-12-23" },
    { title: "Mobile-First Design Strategy", status: "completed", due_date: "2024-12-28" },
    { title: "Implementation: Header & Footer", status: "completed", due_date: "2025-01-02" },
    { title: "Implementation: Hero Section", status: "completed", due_date: "2025-01-05" },
    { title: "Implementation: Services Section", status: "completed", due_date: "2025-01-08" },
    { title: "Implementation: Trust & About", status: "completed", due_date: "2025-01-10" },
    { title: "Content Integration (PT/DE)", status: "completed", due_date: "2025-01-15" },
    { title: "Contact Form & Legal Pages", status: "completed", due_date: "2025-01-18" },
    { title: "Internal Alpha Testing", status: "completed", due_date: "2025-01-20" },
    { title: "Client Review Round 1", status: "completed", due_date: "2025-01-25" },
    { title: "Revision 1 Implementation", status: "completed", due_date: "2025-01-30" },
    { title: "Client Review Round 2", status: "completed", due_date: "2025-02-05" },
    { title: "Revision 2 Implementation", status: "completed", due_date: "2025-02-10" },
    { title: "Final Polish & SEO", status: "pending", due_date: "2025-02-15" },
    { title: "Go-Live (Launch)", status: "pending", due_date: "2025-03-01" },
];

async function createMilestones() {
    console.log(`Creating milestones in: ${supabaseUrl}`);

    // 1. Get Project ID
    const { data: project, error: projError } = await supabase
        .from('projects')
        .select('id')
        .eq('name', 'Ribeiro Consulting Website')
        .single();

    if (projError || !project) {
        console.error('Project not found:', projError);
        return;
    }

    console.log(`Found Project ID: ${project.id}`);

    // 2. Insert/Upsert Milestones
    for (const m of MILESTONES) {
        // Check if exists
        const { data: existing } = await supabase
            .from('milestones')
            .select('id')
            .eq('project_id', project.id)
            .eq('title', m.title)
            .single();

        if (existing) {
            console.log(`Skipping existing: ${m.title}`);
            continue;
        }

        const { error } = await supabase
            .from('milestones')
            .insert({
                project_id: project.id,
                title: m.title,
                status: m.status,
                due_date: m.due_date,
                description: 'Autogenerated from project plan.'
            });

        if (error) {
            console.error(`Error inserting ${m.title}:`, error);
        } else {
            console.log(`Created: ${m.title}`);
        }
    }
}

createMilestones();
