
import { createClient } from '@supabase/supabase-js';
import { faker } from '@faker-js/faker'; // Note: User might not have faker installed, I will try to use native random generation if dependency is an issue, but standard practice is faker.
// Actually, to avoid installing new dependencies if not present, I'll write a simple helper.

import fs from 'fs';
import path from 'path';

// 1. Load Local Env
function parseEnv(filePath: string) {
    const content = fs.readFileSync(filePath, 'utf-8');
    const env: Record<string, string> = {};
    content.split('\n').forEach(line => {
        const match = line.match(/^([^=]+)=(.*)$/);
        if (match) {
            env[match[1].trim()] = match[2].trim();
        }
    });
    return env;
}

const envConfig = parseEnv(path.resolve(process.cwd(), '.env'));
const supabaseUrl = envConfig['NEXT_PUBLIC_SUPABASE_URL'];
const supabaseKey = envConfig['SUPABASE_SERVICE_ROLE_KEY']; // Use Service Role to allow inserting anything

if (!supabaseUrl || !supabaseKey) {
    console.error('Missing Local Keys');
    process.exit(1);
}

// Ensure we are hitting localhost to protect production
if (!supabaseUrl.includes('localhost') && !supabaseUrl.includes('127.0.0.1')) {
    console.error('SAFETY BLOCK: This script is for LOCAL environment only.');
    console.error(`Current URL: ${supabaseUrl}`);
    process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

// Helpers for random data
const randomElement = <T>(arr: T[]) => arr[Math.floor(Math.random() * arr.length)];
const randomInt = (min: number, max: number) => Math.floor(Math.random() * (max - min + 1)) + min;

async function seed() {
    console.log(`🌱 Seeding Local Database: ${supabaseUrl}`);

    // 1. Create Fake Clients
    const clients = [];
    for (let i = 0; i < 5; i++) {
        const companyName = `Test Company ${randomInt(100, 999)}`;
        const { data: client, error } = await supabase
            .from('clients')
            .insert({
                company_name: companyName,
                name: `John Doe ${i}`,
                contact_email: `test.client.${i}@example.com`,
                status: randomElement(['lead', 'in-development', 'maintenance']),
                street_address: `${randomInt(1, 100)} Main St`,
                city: 'Zurich',
                country: 'Switzerland'
            })
            .select()
            .single();

        if (client) {
            console.log(`Created Client: ${client.company_name}`);
            clients.push(client);
        } else {
            console.error('Error creating client', error);
        }
    }

    if (clients.length === 0) return;

    // 2. Create Projects & Invoices
    for (const client of clients) {
        // Create 1-2 projects per client
        const numProjects = randomInt(1, 2);
        for (let p = 0; p < numProjects; p++) {
            const { data: project } = await supabase
                .from('projects')
                .insert({
                    client_id: client.id,
                    name: `${client.company_name} Website V${p + 1}`,
                    status: 'active',
                    description: 'A test project generated by seed script.'
                })
                .select()
                .single();

            if (project) {
                console.log(`  > Created Project: ${project.name}`);

                // Create Invoice
                const { data: invoice } = await supabase
                    .from('invoices')
                    .insert({
                        client_id: client.id,
                        project_id: project.id,
                        amount: randomInt(1000, 5000),
                        status: randomElement(['pending', 'paid', 'sent']),
                        due_date: new Date(Date.now() + 86400000 * 30).toISOString(),
                        payment_plan_enabled: Math.random() > 0.5
                    })
                    .select()
                    .single();

                if (invoice) {
                    console.log(`    > Created Invoice: ${invoice.amount} CHF`);

                    // Log activity
                    await supabase.from('activity_logs').insert({
                        action: 'create_invoice',
                        entity_type: 'invoice',
                        entity_id: invoice.id,
                        metadata: { amount: invoice.amount, generated: true }
                    });
                }
            }
        }
    }

    console.log('✅ Seeding Complete.');
}

seed();
